export default {
  WIN_SCORE: 5,
  FRAME_TIME_THRESHOLD : 0.01,
  MAX_PEDDLE_SPEED : 60,
  PEDDLE_ACCEL : 15,
  PEDDLE_DECEL_RATIO : 0.5,
  SOUND_EFFECT_THRESHOLD : 0.3,
  SAFE_WALL_STUCK_THRESHOLD : 4,
  MAX_BALL_SPEED : 100,
  MIN_BALL_SPEED : 10,
  BALL_PREPARE_MS: 1000
}

